// Mock Supabase database for testing
export const MockedSupabaseDb = jest.fn().mockImplementation(() => ({
  getHabits: jest.fn().mockResolvedValue([]),
  createHabit: jest.fn(),
  updateHabit: jest.fn(),
  reorderHabits: jest.fn(),
  deleteHabit: jest.fn(),
  createHabitCompletion: jest.fn(),
  updateHabitCompletion: jest.fn(),
  getHabitCompletionsByDate: jest.fn(),
  getHabitCompletionsById: jest.fn(),
  deleteHabitCompletion: jest.fn(),
  createExercise: jest.fn(),
  getExercises: jest.fn().mockResolvedValue([]),
  updateExercise: jest.fn(),
  reorderExercises: jest.fn(),
  deleteExercise: jest.fn(),
  createSet: jest.fn(),
  getSetsByExerciseId: jest.fn().mockResolvedValue([]),
  updateSet: jest.fn(),
  deleteSet: jest.fn(),
  createTask: jest.fn(),
  getTasks: jest.fn().mockResolvedValue([]),
  getTask: jest.fn().mockResolvedValue(null),
  updateTask: jest.fn(),
  deleteTask: jest.fn(),
  getTags: jest.fn().mockResolvedValue([]),
  createTag: jest.fn(),
  getTaskTagIds: jest.fn().mockResolvedValue([]),
  setTaskTags: jest.fn().mockResolvedValue(undefined),
  getTaskTagIdsMap: jest.fn().mockResolvedValue({}),
  deleteTag: jest.fn().mockResolvedValue(undefined),
  setOnFetchingStateChange: jest.fn(),
  initialize: jest.fn().mockResolvedValue(undefined),
  getIsFetchingUser: jest.fn().mockReturnValue(false),
}));

