
export type AutoGeneratedFields = {
  id: number;
  created_at?: string;
  updated_at?: string;
}

export type Habit = AutoGeneratedFields & {
  name: string;
  order: number;
  countTarget?: number;
}

export type HabitCompletion = AutoGeneratedFields & {
  habitId: number;
  completionDate: string;
  count?: number;
}

export type HabitInput = Omit<Habit, keyof AutoGeneratedFields>
export type HabitCompletionInput = Omit<HabitCompletion, keyof AutoGeneratedFields>

export abstract class HabitDatabaseInterface {
  // Habit operations
  abstract createHabit(habit: { name: string }): Promise<Habit>
  abstract getHabits(): Promise<Habit[]>
  abstract updateHabit(id: number, updates: Partial<HabitInput>): Promise<Habit>
  abstract reorderHabits(habits: Habit[]): Promise<Habit[]>
  abstract deleteHabit(id: number): Promise<void>

  // HabitCompletion operations
  abstract createHabitCompletion(habitCompletion: HabitCompletionInput): Promise<HabitCompletion>
  abstract updateHabitCompletion(id: number, updates: Partial<HabitCompletionInput>): Promise<HabitCompletion>
  abstract getHabitCompletionsByDate(completionDate?: string): Promise<HabitCompletion[]>
  abstract getHabitCompletionsById(habitId: number): Promise<HabitCompletion[]>
  abstract deleteHabitCompletion(id: number): Promise<void>
}
