export type AutoGeneratedFields = {
  id: number;
  created_at?: string;
  updated_at?: string;
}

export type Habit = AutoGeneratedFields & {
  name: string;
  order: number;
  countTarget?: number;
}

export type HabitCompletion = AutoGeneratedFields & {
  habitId: number;
  completionDate: string;
  count?: number;
}

export type HabitInput = Omit<Habit, keyof AutoGeneratedFields>
export type HabitCompletionInput = Omit<HabitCompletion, keyof AutoGeneratedFields>

// Exercise & Set (workouts)
export type Exercise = AutoGeneratedFields & {
  name: string;
  order: number;
}

export type Set = AutoGeneratedFields & {
  exerciseId: number;
  weight: number | null;
  reps: number;
  completionDate: string; // ISO date only, e.g. "2025-02-22"
}

export type ExerciseInput = Omit<Exercise, keyof AutoGeneratedFields>;
export type SetInput = Omit<Set, keyof AutoGeneratedFields>;
