-- Tags table (user-scoped)
CREATE TABLE IF NOT EXISTS public.tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS tags_user_id_idx ON public.tags (user_id);

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own tags"
  ON public.tags FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own tags"
  ON public.tags FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own tags"
  ON public.tags FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own tags"
  ON public.tags FOR DELETE
  USING (auth.uid() = user_id);

-- Task-tag junction table
CREATE TABLE IF NOT EXISTS public.task_tags (
  task_id bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, tag_id)
);

CREATE INDEX IF NOT EXISTS task_tags_task_id_idx ON public.task_tags (task_id);
CREATE INDEX IF NOT EXISTS task_tags_tag_id_idx ON public.task_tags (tag_id);

ALTER TABLE public.task_tags ENABLE ROW LEVEL SECURITY;

-- Users can only access task_tags for their own tasks and tags
CREATE POLICY "Users can view own task_tags"
  ON public.task_tags FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.tasks t WHERE t.id = task_id AND t.user_id = auth.uid())
    AND EXISTS (SELECT 1 FROM public.tags g WHERE g.id = tag_id AND g.user_id = auth.uid())
  );

CREATE POLICY "Users can insert own task_tags"
  ON public.task_tags FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.tasks t WHERE t.id = task_id AND t.user_id = auth.uid())
    AND EXISTS (SELECT 1 FROM public.tags g WHERE g.id = tag_id AND g.user_id = auth.uid())
  );

CREATE POLICY "Users can delete own task_tags"
  ON public.task_tags FOR DELETE
  USING (
    EXISTS (SELECT 1 FROM public.tasks t WHERE t.id = task_id AND t.user_id = auth.uid())
  );
